-- Waste Release 2021 Data Cleaning with SQL 
-- Techniques used - ROW_NUMBER, Case Statements, Alter Table, Update, Add, Delete, Is Null

-- Copy table to use for data transformation 
SELECT * 
INTO WasteCopy
FROM Waste

-- View the Data
SELECT *
FROM WasteCopy

-- Check Unit of Measure 
-- Can see majority of the data is in Pounds only a few are in Grams 
SELECT [UNIT OF MEASURE], COUNT([UNIT OF MEASURE])
FROM WasteCopy
GROUP BY [UNIT OF MEASURE]

--Covert all Waste Production Values to Pounds for all columns needed
-- Fugitive Air 
UPDATE WasteCopy
SET [FUGITIVE AIR]= CASE WHEN [UNIT OF MEASURE] = 'Grams' THEN [FUGITIVE AIR]/453.6
ELSE [FUGITIVE AIR]
END

-- Stack Air 
UPDATE WasteCopy
SET [STACK AIR]= CASE WHEN [UNIT OF MEASURE] = 'Grams' THEN [STACK AIR]/453.6
ELSE [STACK AIR]
END

--Water 
UPDATE WasteCopy
SET WATER= CASE WHEN [UNIT OF MEASURE] = 'Grams' THEN WATER/453.6
ELSE WATER
END

--Underground CL I
UPDATE WasteCopy
SET [UNDERGROUND CL I]= CASE WHEN [UNIT OF MEASURE] = 'Grams' THEN [UNDERGROUND CL I]/453.6
ELSE [UNDERGROUND CL I]
END

--Underground C II-V
UPDATE WasteCopy
SET [UNDERGROUND C II-V]= CASE WHEN [UNIT OF MEASURE] = 'Grams' THEN [UNDERGROUND C II-V]/453.6
ELSE [UNDERGROUND C II-V]
END

--RCRA C LANDFILL
UPDATE WasteCopy
SET [RCRA C LANDFILL]= CASE WHEN [UNIT OF MEASURE] = 'Grams' THEN [RCRA C LANDFILL]/453.6
ELSE [RCRA C LANDFILL]
END

--Other Landfills
UPDATE WasteCopy
SET [OTHER LANDFILLS]= CASE WHEN [UNIT OF MEASURE] = 'Grams' THEN [OTHER LANDFILLS]/453.6
ELSE [OTHER LANDFILLS]
END

--Land Treatment 
UPDATE WasteCopy
SET [LAND TREATMENT]= CASE WHEN [UNIT OF MEASURE] = 'Grams' THEN [LAND TREATMENT]/453.6
ELSE [LAND TREATMENT]
END

--RCRA Surface IM 
UPDATE WasteCopy
SET [RCRA SURFACE IM]= CASE WHEN [UNIT OF MEASURE] = 'Grams' THEN [RCRA SURFACE IM]/453.6
ELSE [RCRA SURFACE IM]
END

--Other Surfaces 
UPDATE WasteCopy
SET [OTHER SURFACE I]= CASE WHEN [UNIT OF MEASURE] = 'Grams' THEN [OTHER SURFACE I]/453.6
ELSE [OTHER SURFACE I]
END

-- Other Disposal 
UPDATE WasteCopy
SET [OTHER DISPOSAL]= CASE WHEN [UNIT OF MEASURE] = 'Grams' THEN [OTHER DISPOSAL]/453.6
ELSE [OTHER DISPOSAL]
END

--On-Site Release Total 
UPDATE WasteCopy
SET [ON-SITE RELEASE TOTAL]= CASE WHEN [UNIT OF MEASURE] = 'Grams' THEN [ON-SITE RELEASE TOTAL]/453.6
ELSE [ON-SITE RELEASE TOTAL]
END

--Off-Site Release Total 
UPDATE WasteCopy
SET [OFF-SITE RELEASE TOTAL]= CASE WHEN [UNIT OF MEASURE] = 'Grams' THEN [OFF-SITE RELEASE TOTAL]/453.6
ELSE [OFF-SITE RELEASE TOTAL]
END


--Total Release
UPDATE WasteCopy
SET [TOTAL RELEASES]= CASE WHEN [UNIT OF MEASURE] = 'Grams' THEN [TOTAL RELEASES]/453.6
ELSE [TOTAL RELEASES]
END

-- Remove Columns not used 
ALTER TABLE WasteCopy
DROP Column [POTW - TRNS RLSE], [POTW - TRNS TRT], [POTW - TOTAL TRANSFERS], 
[OFF-SITE RECYCLED TOTAL], [OFF-SITE TREATED TOTAL], [TOTAL TRANSFER],
RELEASES, [ON-SITE CONTAINED], [OFF-SITE CONTAIN], [OFF-SITE OTHER R], 
[ENERGY RECOVER OF], [ENERGY RECOVER ON], [RECYCLING ON SITE], [RECYCLING OFF SIT], 
[TREATMENT ON SITE], [TREATMENT OFF SITE], [PRODUCTION WSTE (8#1-8#7)], [ONE-TIME RELEASE], 
[ON-SITE RELEASE TOTAL1], [OFF-SITE RELEASE TOTAL1], [TOTAL RELEASES1]

-- Update the Unit of Measure to Pounds
UPDATE WasteCopy
SET [UNIT OF MEASURE]= CASE WHEN [UNIT OF MEASURE] = 'Grams' THEN 'Pounds'
ELSE [UNIT OF MEASURE]
END

-- Combine Columns into a new column
-- Total Air
ALTER TABLE WasteCopy
ADD [TOTAL AIR] FLOAT;

UPDATE WasteCopy 
SET [TOTAL AIR] = [FUGITIVE AIR] + [STACK AIR]

-- Total Underground
ALTER TABLE WasteCopy
ADD [TOTAL UNDERGROUND] FLOAT;

UPDATE WasteCopy 
SET [TOTAL UNDERGROUND] = [UNDERGROUND CL I] + [UNDERGROUND C II-V]

--Total Landfill
ALTER TABLE WasteCopy
ADD [TOTAL LANDFILL] FLOAT;

UPDATE WasteCopy 
SET [TOTAL LANDFILL] = [RCRA C LANDFILL] + [OTHER LANDFILLS]

-- Total Surface Impoundment
ALTER TABLE WasteCopy
ADD [TOTAL SURFACE IMPOUNDMENT] FLOAT;

UPDATE WasteCopy 
SET [TOTAL SURFACE IMPOUNDMENT] = [RCRA SURFACE IM] + [OTHER SURFACE I]

-- Check for null values in total release
SELECT * 
FROM WasteCopy
WHERE [TOTAL RELEASES] is null 

-- Remove all rows that have total release = 0
DELETE  
FROM WasteCopy
WHERE [TOTAL RELEASES] = 0


-- Check for duplicates 
WITH row_numCTE AS(
SELECT *, 
ROW_NUMBER() OVER(
PARTITION BY 
	ID,
	[TOTAL RELEASES]
	ORDER BY [TOTAL RELEASES]) as row_num
FROM WasteCopy)

SELECT * 
FROM row_numCTE
WHERE row_num > 1
ORDER BY ID